### ISSUE TITLE
str.join function

### ISSUE THREAD

**Issue by Nicolai-vKuegelgen** [MolecularBioinformatics/PyCopasi#1]
The str.join function only supports one iterable as an argument. (https://docs.python.org/3.5/library/stdtypes.html#str.join)

In line 28 the function is called with 3 arguments [ join(row, column, values)].
Changing the call a tuple of these 3 arguments [join((row, column, values))] fixes the issue.

Problem occured with Python 3.5.2 on Windows 7, 64-bit (Anaconda instllation).

**Comment by mathiasbockwoldt** [comment]
You are correct, sir. I fixed it with commit 16bb2d3 .
For the next time, please tell me the file name. The failure is then easier to find :wink:
